### ISSUE TITLE
Allow quotes in .env file

### ISSUE THREAD

**Issue by eberkund** [purpliminal/rust-dotenv#87]
dotenv libraries in other languages allow quotes without affecting the value.

For example,

    SOME_VALUE="hello"
    OTHER_VALUE=hello

In rust-dotenv `OTHER_VALUE` will have a value `hello` where `SOME_VALUE` will have a value of `"hello"`. I think the behaviour should be changed to be consistent with other dotenv libraries.

**Comment by daboross** [comment]
This should be the case in the latest release of `rust-dotenv`. It used to be an issue (see https://github.com/purpliminal/rust-dotenv/issues/31), but it should be fixed in all versions 0.9+.

What version of `dotenv` are you depending on?

**Comment by eberkund** [comment]
Using 0.11

    [dependencies]
    dotenv = "0.11.0"
    dotenv_codegen = "0.11.0"

It seems to be an issue only when using the macro syntax

    extern crate dotenv;
    #[macro_use]
    extern crate dotenv_codegen;

    fn main() {
        println!("{}", dotenv!("SOME_VALUE"));
        println!("{}", dotenv!("OTHER_VALUE"));
    }

Outputs:

    "hello"
    hello

**Comment by daboross** [comment]
Alright - this is definitely a bug. It seems that the `dotenv_codegen` crate was depending on a way earlier version of `dotenv`!

Should be fixed by #88 once that's merged.

Thanks for reporting!

**Comment by purpliminal** [comment]
Fixed by #91.

**Comment by FallingSnow** [comment]
Just a notice, this issue still exists in `dotenv_codegen 0.11.0` which is the latest version on crates.io.
